construction/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
import services.views
import contact.views
import gallery.views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', services.views.home, name='home'),
    url(r'^services/', services.views.services, name='services'),
    url(r'^about/', services.views.about, name='about'),
    url(r'^contact/', contact.views.contact, name='contact'),
    url(r'^gallery/', gallery.views.gallery, name='gallery'),
    url(r'^service_detail/(?P<slug>[\w-]+)/$', services.views.service_detail, name='service_detail'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.db import models

# Create your models here.

displays/models.py
from django.db import models


# Create your models here.
class DisplayImage(models.Model):
    slider_image = models.ImageField(upload_to='slider/images/')
    header_text = models.CharField(max_length=120, null=True, blank=True)
    text = models.CharField(max_length=120, null=True, blank=True)
    about_display = models.BooleanField(default=False)
    active_slides = models.BooleanField(default=True)
    home_background_display = models.BooleanField(default=False)

    def __str__(self):
        return str(self.active_slides)


class Logo(models.Model):
    logo_image = models.ImageField(upload_to="logo/images/")
    title = models.CharField(max_length=120)
    active = models.BooleanField(default=True)

    def __str__(self):
        return str(self.active)

gallery/models.py
from django.db import models


class Portfolio(models.Model):
    project_title = models.CharField(max_length=100)
    description = models.TextField(max_length=1500)
    project_date = models.DateField()
    project_image = models.ImageField(upload_to='portfolio/images/')
    slug = models.SlugField(unique=True)
    display = models.BooleanField(default=False)

services/models.py
from django.db import models
from ckeditor.fields import RichTextField


class Service(models.Model):
    title = models.CharField(max_length=120)
    description = RichTextField(max_length=1500)
    slug = models.SlugField(unique=True)
    active = models.BooleanField()
    display = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class ServicesImage(models.Model):
    title = models.ForeignKey(Service)
    image = models.ImageField(upload_to='services/images/')
    active = models.BooleanField(default=True)

contact/forms.py
from django import forms


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    contact_email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)
    cc_myself = forms.BooleanField(required=False)

contact/views.py
from django.shortcuts import render
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from .forms import ContactForm


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            contact_email = form.cleaned_data['contact_email']
            cc_myself = form.cleaned_data['cc_myself']

            recipients = ['mukwazhi@gmail.com']
            if cc_myself:
                recipients.append(contact_email)

            if subject and message and contact_email and recipients:
                try:
                    send_mail(subject, message, contact_email, [recipients])
                except BadHeaderError:
                    return HttpResponse('Invalid header found.')
                return HttpResponseRedirect('/contact/thanks/')
        else:
            return HttpResponse('Make sure all fields are entered and valid.')
    else:
        form = ContactForm

    context = {
        'form': form,
    }
    template = 'contact.html'

    return render(request, template, context)

displays/views.py
from django.shortcuts import render

# Create your views here.

gallery/views.py
from django.shortcuts import render
from .models import Portfolio


def gallery(request):
    portfolio = Portfolio.objects.all()
    return render(request, 'gallery.html', {'portfolio': portfolio})

services/views.py
from django.shortcuts import render
from .models import Service, ServicesImage
from displays.models import DisplayImage
from gallery.models import Portfolio


def home(request):
    slider =  DisplayImage.objects.all()
    services = Service.objects.all()
    images = ServicesImage.objects.all()
    portfolio = Portfolio.objects.all()

    context = {"slider": slider,
               'services': services,
               'images': images,
               'portfolio': portfolio,
               }
    return render(request, 'home.html', context)

def services(request):
    services = Service.objects.all()
    images = ServicesImage.objects.all()
    slider = DisplayImage.objects.all()
    context = {
        'services': services,
        'images': images,
        'slider':slider
    }
    return render(request, 'services.html', context)

def about(request):
    slider = DisplayImage.objects.all()

    return render(request, 'about.html', {"slider":slider})

def service_detail(request, slug):
    service = Service.objects.get(slug=slug)
    image = ServicesImage.objects.all()
    context = {
        'service': service,
        'image': image,
    }
    return render(request, 'service_detail.html', context)

contact/templates/contact.html
{% extends 'base.html' %}
{% block title %} Contact Us {% endblock %}
{% load bootstrap %}
{% load staticfiles %}

{% block content %}
<div class="container" style="margin-top: 60px">
<div class="col-md-12">
    <div id="googleMap" style="width:100%;height:380px; margin-bottom: 10px;"></div>
</div>
   <div class="row">
			<div class="col-md-4">
				<div class="panel" style="">
					<div class="panel-heading" style="background-color: #f5f5f5;">
						<h3><span class="glyphicon glyphicon-map-marker" style="padding-right: 10px; color: #337AB7"></span>Visit Our Office</h3>
					</div>
					<div class="panel-body" style=" box-sizing: border-box;">
						<address>
						<p><strong>Head Office.</strong></p>
						<p>742 Evergreen Terrace</p>
						<p>Springfield</p>
						<p>, Springfield</p>
						<i class="icon-phone-sign"></i> +(263) 773 466 035 n.
						</address>
                        <br>
					</div>
				</div>
    </div>
         <div class="col-md-4"  >
         <div class="panel">
				<div class="panel-heading"  style="background-color: #f5f5f5;">
				  <h3><span class="glyphicon glyphicon-envelope" style="padding-right: 10px; color: #F96;"></span>Email Us</h3>
				</div>
				<div class="panel-body">
	{{ form.non_field_errors }}
    <form role="form" action="" method="post" >{% csrf_token %}
			<div class="fieldWrapper">
			{{ form.subject.errors }}
			<!--<label for="{{ form.subject.id_for_label }}">Email subject:</label>-->
			{{ form.subject|bootstrap }}
			</div>
			<div class="fieldWrapper">
			{{ form.message.errors }}
			<!--<label for="{{ form.message.id_for_label }}">Your message:</label>-->
			{{ form.message|bootstrap }}
			</div>
			<div class="fieldWrapper">
			{{ form.sender.errors }}
			<!--<label for="{{ form.sender.id_for_label }}">Your email address:</label>-->
			{{ form.contact_email|bootstrap }}
			</div>
			<div class="fieldWrapper">
			{{ form.cc_myself.errors }}
			<!--<label for="{{ form.cc_myself.id_for_label }}">CC yourself?</label>-->
			{{ form.cc_myself|bootstrap }}
			</div>
    <button type="submit" class="btn btn-info">Submit</button>

    </form>
    </div>
             </div>
        </div>

       <div class="col-md-4" >
           <div class="panel" style="box-sizing: border-box;">
				<div class="panel-heading"style="background-color: #f5f5f5;">
				  <h3><span class="glyphicon glyphicon-time" style="color: #337AB7;"></span> Business hours</h3>
				</div>
				<div class="panel-body">
					<table class="table table-hover">
					  <thead>
						<tr>

						  <th>Day</th>
						  <th>Time</th>
						</tr>
					  </thead>
					  <tbody>
						<tr class="success">
						  <td>Monday</td>
						  <td>9:00 to 18:00</td>
						</tr>
						<tr class="success">
						  <td>Tuesday</td>
						  <td>9:00 to 18:00</td>
						</tr>
						<tr class="success">

						  <td>Wednesday</td>
						  <td>9:00 to 18:00</td>
						</tr>
						<tr class="success">

						  <td>Thursday</td>
						  <td>9:00 to 18:00</td>
						</tr>
						<tr class="success">

						  <td>Friday</td>
						  <td>9:00 to 18:00</td>
						</tr>
						<tr class="warning">

						  <td>Saturday</td>
						  <td>9:00 to 14:00</td>
						</tr>
						<tr class="danger">

						  <td>Sunday</td>
						  <td>day off</td>
						</tr>
					  </tbody>
					</table>
					</div>
				</div>
			</div>
	</div>


</div>
{% endblock %}

gallery/templates/gallery.html
{% extends 'gallery_base.html'%}
{% block title %} Gallery {% endblock %}
{% load staticfiles %}

{% block gallery-content %}
<div class="body2">
<div class="container gallery">
    <h1>Our Project Gallery </h1>
    <blockquote>
        <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
            dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
            ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
            nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit
            anim id est laborum."</p>
    </blockquote>

    <!-- The container for the list of example images -->
    <div id="links">
    {% for item in portfolio %}
        <div class="col-md-3" style="margin-bottom: 2px;">
            <figure>
            <a href="{{MEDIA_URL}}{{item.project_image}}" title="{{item.project_title}}" data-gallery>
                <img src="{{MEDIA_URL}}{{item.project_image}}" width="200" height="150">
            </a>
                <figcaption>{{item.project_title}}</figcaption>
            </figure>
        </div>
    {% endfor %}
    </div>

    <br>
</div>
<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
    <br>
    </div>
{% endblock %}

gallery/templates/gallery_base.html
<!DOCTYPE HTML>
<html lang="en">
<head>
<!--[if IE]>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<![endif]-->
<meta charset="utf-8">
<title>Construction&Co |{% block title %} {% endblock %}</title>
    {% load staticfiles %}
<meta name="description" content="Construction&Co is a civil and construction company that specializes in construction, architecture, civil engineering, interior decor and design, renovations, warehouse
    construction, project management, contract management, quantity surveying and estimations, project consulting and building inspections.">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'gallery/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'gallery/css/blueimp-gallery.min.css' %}">
<link rel="stylesheet" href="{% static 'gallery/css/bootstrap-image-gallery.css' %}">
<link rel="stylesheet" href="{% static 'gallery/css/gallery.css' %}">
    <link rel="stylesheet" href="{% static 'gallery/css/lora.css' %}">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lora" />
</head>
<body>
{% include 'navbar.html' %}
{% block gallery-content %}

{% endblock %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="{% static 'gallery/js/jquery.min.js' %}"></script>
<script src="{% static 'gallery/js/bootstrap.min.js' %}"></script>
<script src="{% static 'gallery/js/jquery.blueimp-gallery.min.js' %}"></script>
<script src="{% static 'gallery/js/bootstrap-image-gallery.js' %}"></script>
{% include 'footer.html'%}
</body>
</html>

services/templates/about.html
{%extends 'base.html'%}
{% block title %} About Us {% endblock %}


{% block content %}
    {% for slider in slider %}
    {% if slider.about_display %}
    <div class="jumbotron about" style="background-image: url('{{MEDIA_URL}}{{slider.slider_image}}'); height: 400px;">
      <div class="container" >
        <h1 class="display-3">Construction & Co </h1>

      </div>
    </div>
{% endif %}
{% endfor %}
    <div class="container">

            <article class="top-box">
                <section>
                    <h1>About Us</h1>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vel varius elit, at rutrum nisl.
                        Maecenas maximus a mauris at dapibus. Phasellus ac fermentum velit. Vestibulum dapibus augue id
                        diam fringilla auctor ac a metus. Nulla aliquam vestibulum pretium. Phasellus imperdiet egestas
                        massa a vestibulum. Etiam lacinia nisl arcu. Maecenas lacinia tortor et tincidunt ultrices.
                        Donec mi eros, aliquet nec volutpat ac, dignissim a quam. Curabitur egestas nisi augue, quis
                        posuere odio consequat sed. Nam dictum non nibh ut lobortis. Lorem ipsum dolor sit amet,
                        consectetur adipiscing elit. Fusce elementum tortor a sapien pharetra, eget pellentesque
                        enim maximus. Nam dictum arcu ac iaculis sodales. Nunc eu ligula feugiat, dapibus orci tristique,
                        facilisis urna.</p>
                </section>
                <section>
                    <h2>History</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vel varius elit, at rutrum nisl.
                        Maecenas maximus a mauris at dapibus. Phasellus ac fermentum velit. Vestibulum dapibus augue id
                        diam fringilla auctor ac a metus. Nulla aliquam vestibulum pretium. Phasellus imperdiet egestas
                        massa a vestibulum. Etiam lacinia nisl arcu. Maecenas lacinia tortor et tincidunt ultrices.
                        Donec mi eros, aliquet nec volutpat ac, dignissim a quam. Curabitur egestas nisi augue, quis
                        posuere odio consequat sed. Nam dictum non nibh ut lobortis. Lorem ipsum dolor sit amet,
                        consectetur adipiscing elit. Fusce elementum tortor a sapien pharetra, eget pellentesque
                        enim maximus. Nam dictum arcu ac iaculis sodales. Nunc eu ligula feugiat, dapibus orci tristique,
                        facilisis urna.</p>
                </section>
                <section>
                    <h2>Awards</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vel varius elit, at rutrum nisl.
                        Maecenas maximus a mauris at dapibus. Phasellus ac fermentum velit. Vestibulum dapibus augue id
                        diam fringilla auctor ac a metus. Nulla aliquam vestibulum pretium. Phasellus imperdiet egestas
                        massa a vestibulum. Etiam lacinia nisl arcu. Maecenas lacinia tortor et tincidunt ultrices.
                        Donec mi eros, aliquet nec volutpat ac, dignissim a quam. Curabitur egestas nisi augue, quis
                        posuere odio consequat sed. Nam dictum non nibh ut lobortis. Lorem ipsum dolor sit amet,
                        consectetur adipiscing elit. Fusce elementum tortor a sapien pharetra, eget pellentesque
                        enim maximus. Nam dictum arcu ac iaculis sodales. Nunc eu ligula feugiat, dapibus orci tristique,
                        facilisis urna..</p>
                </section>
            </article>
    </div>
{% endblock %}

services/templates/home.html
{% extends 'base.html'%}
{% load staticfiles %}
{% block title %} Home {% endblock %}

  {% block content %}
    <!-- Carousel -->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
       <ol class="carousel-indicators">
         {% for slidr in slider %}
            {% if slidr.active_slides %}
         <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter }}"
             {% if forloop.first %}class="active"{% endif %}></li>
           {% endif %}
         {% endfor %}
       </ol>

      <div class="carousel-inner" role="listbox">
          {% for slidr in slider %}
          {% if slidr.active_slides %}
             <div class="item {% if forloop.first %}active{% endif %}">
                 <img class="slide-image" src="{{ MEDIA_URL }}{{ slidr.slider_image }}" alt="...">
             </div>
          {% endif %}
          {% endfor %}
        </div>

      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>

     <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->
     <div class="divider">
         <div class="container" >
            <br>
            <H1><b>Construction is our way of life ~ Help us live it!!</b>
         <a class="btn btn-default pull-right" href="{% url 'contact'%}" role="button">Contact Us &raquo;</a></H1>
             </div>
        </div>

    <!-- Marketing messaging and featurettes
    ================================================== -->
    {% for slidr in slider %}
        {% if slidr.home_background_display %}
     <div class="marketing" style="background-image: url('{{MEDIA_URL}}{{slidr.slider_image}}'); ">
         <div class=container">
         {% endif %}
         {% endfor %}
        <h1><b>Featured Services</b></h1>
     <!-- Three columns of text below the carousel -->
      <div class="row" style="margin-top: 10px;">
          {% for service in services %}
          {% if service.display %}
        <div class="col-md-3" >
            {% for item in service.servicesimage_set.all %}
          <a href="{% url 'service_detail' service.slug  %}" >
              <img class="img-circle" src="{{ MEDIA_URL }}{{ item.image }}" alt="Generic placeholder image" width="140" height="140"></a>
            {% endfor %}
          <h4>{{ service.title }}</h4>
        </div><!-- /.col-lg-4 -->
        {% endif %}
        {% endfor %}
          <a class="btn btn-default pull-right" href="{% url 'services'%}" role="button" style="width: 100%; opacity: 40%">View Services
              <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></a></H1>
      </div><!-- /.row -->
         </div>
         </div>

         <div class="portfolio">
             <br>
                 <div class="container">
                 <div class="col-md-3 gallery">
                 <h2><b>Project Gallery</b></h2>
                     <br>
                    <p>On sait depuis longtemps que travailler avec du texte lisible et contenant du sens est source de
                        distractions, et empêche de se concentrer sur la mise en page elle-même. L'avantage du Lorem
                        Ipsum sur un texte générique comme 'Du texte. Du texte. Du texte.' est qu'il possède une
                        distribution de lettres plus ou moins normale, et en tout cas comparable avec celle du français
                        standard.</p>
                     <br>
                        <a class="btn btn-default" href="{% url 'gallery' %}" role="button">View Gallery &raquo;</a>
                 </div>
                 <div class="col-md-9" >
                     {% for item in portfolio %}
                     {% if item.display %}
                     <div class="col-md-3">
                         <figure>
                         <a href="{% url 'gallery'%}" ><img src="{{MEDIA_URL}}{{item.project_image}}" width="200" height="150"></a>
                         <figcaption>{{item.project_title}}</figcaption>
                         </figure>
                     </div>
                     {% endif %}
                     {% endfor %}
                 </div>
             </div>
         </div>

        {% for slidr in slider %}
        {% if slidr.home_background_display %}
         <div class="why-us" style="background-image: url('{{MEDIA_URL}}{{slidr.slider_image}}'); height: 400px; ">
             <div class="container">
                 <h1><b>Why Choose Us</b></h1>
                     <div class="col-md-3 ">
                        <h3>On time Delivery </h3>
                         <p>'Lorem Ipsum' vous conduira vers
                        de nombreux sites qui n'en sont encore qu'à leur phase de construction. Plusieurs versions sont
                        apparues avec le temps, parfois par accident, souvent intentionnellement (histoire d'y rajouter
                        de petits clins d'oeil, voire des phrases embarassantes)</p>
                     </div>
                 <div class="col-md-3 ">
                        <h3>Professionalism </h3>
                         <p>'Lorem Ipsum' vous conduira vers
                        de nombreux sites qui n'en sont encore qu'à leur phase de construction. Plusieurs versions sont
                        apparues avec le temps, parfois par accident, souvent intentionnellement (histoire d'y rajouter
                        de petits clins d'oeil, voire des phrases embarassantes)</p>
                     </div>
                 <div class="col-md-3 ">
                        <h3>Goal Oriented </h3>
                         <p>'Lorem Ipsum' vous conduira vers
                        de nombreux sites qui n'en sont encore qu'à leur phase de construction. Plusieurs versions sont
                        apparues avec le temps, parfois par accident, souvent intentionnellement (histoire d'y rajouter
                        de petits clins d'oeil, voire des phrases embarassantes</p>
                     </div>
                 <div class="col-md-3 ">
                        <h3>Efficient </h3>
                         <p>'Lorem Ipsum' vous conduira vers
                        de nombreux sites qui n'en sont encore qu'à leur phase de construction. Plusieurs versions sont
                        apparues avec le temps, parfois par accident, souvent intentionnellement (histoire d'y rajouter
                        de petits clins d'oeil, voire des phrases embarassantes)</p>
                     </div>
             </div>
             {% endif %}
             {% endfor %}
         </div>
      {% endblock %}

services/templates/service_detail.html
{% extends 'base.html'%}
{% block title %}Detailed Info{% endblock %}
{% load staticfiles %}

{% block content %}
<div class="container detail">
     <div class="page-header">
         <h1>{{service.title}}</h1>
     </div>

    <section >
        <div class="col-md-8 service-description">
        <article>
            <header>
                <h2>{{service.title}}</h2>
                <p>{{service.description|safe}}</p>
            </header>
        </article>
          </div>
        <div class="col-md-4 contact">
        <article>
            <h2>Contact Us</h2>
            <p>If you are intrested in this service, Please fell free to contact us</p>
            <a href="#"><h5><span class="glyphicon glyphicon-envelope" style="padding-right: 10px; color: #F96;"></span>Email Us</h5></a>
            <a href="#"><h5><span class="glyphicon glyphicon-map-marker" style="padding-right: 10px; color: #337AB7"></span>Visit Us</h5></a>
            <a href="#"><h5><span class="glyphicon glyphicon-earphone" style="padding-right: 10px; color: #337AB7"></span>Call Us</h5></a>
            <a href="#"> <h5><i class="fa fa-skype " aria-hidden="true"></i> Skype Us</h5></a>
        </article>
        </div>

        <div class="col-md-12">

            <br>
            <h1></h1>

        </div>

    </section>
    </div>

{% endblock %}

services/templates/services.html
{% extends 'base.html' %}
{% block title %} Services {% endblock %}
{% load staticfiles %}
{% block content %}

{% for slider in slider %}
    {% if slider.about_display %}
    <div class="services-main" style="background-image: url('{{MEDIA_URL}}{{slider.slider_image}}');">
    {% endif %}
{% endfor %}

    <div class="container">
<h1>Featured Services</h1>
    {% for service in services %}
    <div class="col-md-3 services">
            {% for item in service.servicesimage_set.all %}
          <a href="{% url 'service_detail' service.slug %}">
        <img class="img-circle" src="{{MEDIA_URL}}{{item.image}}" style="height: 100px; width: 100px; "></a>
            <h4>{{service.title}}</h4>
            {% endfor %}
            <br>
        </div>
    {% endfor %}
</div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Construction&Co |{% block title%}  {% endblock%}</title>
    {% load staticfiles %}
    <!-- Bootstrap core CSS -->
    <link href=" {% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href='{% static "css/bootstrap.css" %}' />
    <link rel="stylesheet" href='{% static "css/custom.css" %}' />
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lora" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/lora.css' %}">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="http://maps.googleapis.com/maps/api/js"></script>
    <!-- Custom styles for this template -->
    <link href='{% static "css/carousel.css" %}' rel="stylesheet">
  </head>

  <body>
  {% include 'navbar.html'%}
  {% block content%}


{% endblock %}
  {% include 'footer.html'%}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src='{% static "js/jquery.js"%}'></script>
   <script src='{% static "js/custom.js"%}'></script>
    <script src='{% static "js/jquery.min.js"%}'></script>
    <!-- Bootstrap Core JavaScript-->
    <script src='{% static "js/bootstrap.js"%}'></script>
    <script src='{% static "js/bootstrap.min.js"%}'></script>
  </body>
</html>

templates/navbar.html
 <div class="navbar-wrapper">
      <div class="container">

        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#"><b><i>Construction&Co</i></b></a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'services' %}">Services</a></li>
                <li><a href="{% url 'gallery' %}">Gallery</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'contact' %}">Contacts</a></li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </div>